---
title: "Exercices pratiques sur le module 5 : Transformation des données - Biométrie humaine"
author: "..."
date: "..."
output: html_document
---

<!--- NOTE
A chaque fois que cela se justifie, utilisez un chainage des opérations ! 
Prenez soin d'écrire un code clair, lisible, et qui utilise les fonctions ad hoc de manière optimale (recherchez une solution concise et efficace).
--->

```{r setup}
SciViews::R
```

# Remaniement des données

<!--- Consignes 
Importer le jeu de données biometry depuis le package BioDataScience en utilisant l'option lang="FR". Assigez le à biometry. 
--->

```{r importation}

```

<!--- Consignes
Visualisez les 10 premières lignes de biometry pour prendre connaissance du contenu du jeu de données. 
--->

```{r tableau}

```

<!--- Consignes
Calculer l'IMC (BMI en anglais) dans la population étudiée et créez une variable afin d'y associer l'interprétation fournie par l'OMS (dans une variable nommée bmi).
--->

```{r imc}

```


<!--- Consignes
Dénombrez les hommes et les femmes dans chacune de ces catégories d'IMC.
Présentez ce tableau correctement dans le document R Markdown (formattage et légende du tableau). 
--->

```{r imc_tab}

```

<!--- Consignes
Choississez ensuite le graphique le plus adapté et ajoutez-lui une légende pour représenter graphiquement votre tableau. 
--->

```{r imc_graph}

```

<!--- Consignes 
Commentez le tableau et le graphique que vous venez de réaliser en maximum 5 phrases.
--->




<!--- Consignes
Représentez graphiquement l'âge des individus de la manière la plus judicieuse pour déterminer s'il existe plusieurs modes dans le jeu de données. Commentez votre graphique en maximum 5 phrases.
--->

```{r age}

```

<!--- Consignes
Calculez une nouvelle variable qualitative qui sépare les données en fonction de sous-populations représentatives de ces différents modes. Cette variable doit être encodée sous forme de facteur ordonné avec les niveaux classés par âge croissant.
--->

```{r age_group}

```

<!--- Consignes
Créez un tableau qui résume les caractéristiques principales de ces sous-populations : nombre d'observations et IMC moyen. Commentez votre tableau en maximum 5 phrases.
--->

```{r age_imc}

```

<!--- Consignes
Extrayez un sous-tableau contenant uniquement le sous-groupe le plus jeune. Ensuite, éliminez les autres niveau de la variable que vous avez créée dans ce tableau réduit. Réduisez encore ce tableau en ne gardant que les variables gender, age et bmi.
--->

```{r jeune}

```

