---
title: "Exercices pratiques sur le module 5 : Transformation des données - Croissance des coraux"
author: "..."
date: "..."
output: html_document
---


```{r setup}
SciViews::R
```

# Remaniement des données

<!--- Consignes 
Importez-le jeu de données à partir de la copie local au format rds que vous avez enregistrée dans votre dossier docs et assigez-le à coral. 
--->

```{r importation}

```

<!--- Consignes 
Visualisez les variables de votre jeu de données avec la fonction `skim()``
--->

```{r visu_var}

```

<!--- Consignes
Transformez la variable localisation et la variable species en variable facteur. 
--->

```{r factor}

```

<!--- Consignes 
Réalisez un tableau réduit en retirant les variables salinity, température et date du tableau principale. 
--->

```{r selection}

```

<!--- Consignes
Affichez dans votre rapport les 10 premières lignes du tableau que vous venez de réaliser 
--->

```{r tableau}

```

<!--- Consignes
A partir du tableau que vous venez de créer retires les valeurs négatives présentent dans la variable gain. 
--->

```{r filtrer}

```

<!--- Consignes
Calculez les variables suivantes que vous ajoutez au tableau de base. 
1) Divisez le gain de masse par le nombre de jour d'expérience.
2) Divisez le gain de masse standardisé par le nombre de jour d'expérience et multipliez cette nouvelle variable par 100 pour obtenir la croissance en pourcent par jour. 
---> 

```{r calculer}

```

<!--- Consignes
Réalisez au minimum deux tableaux résumant les données par aquarium et par espèce. Ces tableaux devront contenir le nombre d'observation, la valeur minimale, la valeur maximale, la médiane et la moyenne. 
N'oubliez pas d'interpréter chacun des tableaux que vous aurez réalisé en maximum 5 phrases. 
--->

```{r tab1}

```

```{r tab2}

```
